export const longText = `

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus diam metus, scelerisque et pretium non, laoreet et sem. Aenean vehicula ullamcorper elit, ac condimentum tellus bibendum nec. Nullam gravida vehicula sem. Aenean efficitur erat gravida diam condimentum, a consectetur massa egestas. In tincidunt malesuada leo at blandit. Donec non leo nunc. Cras tempus velit dolor, non hendrerit dui vestibulum vitae. Duis non eros lacus. Nunc augue diam, congue rhoncus hendrerit eget, vehicula sit amet diam. Integer ornare luctus pharetra. Etiam nibh ipsum, euismod in leo ut, pharetra hendrerit odio.

Sed mi ligula, auctor a fringilla vitae, porttitor a velit. Vivamus vulputate placerat purus ut eleifend. Integer feugiat purus ut augue convallis, euismod hendrerit ipsum sodales. Nam varius vehicula sapien. Proin viverra elementum risus, vel venenatis odio hendrerit sed. Fusce ultrices non ipsum sed dignissim. Duis placerat sem vel enim scelerisque efficitur. Ut ullamcorper porttitor pellentesque. Nulla porttitor felis vel mi laoreet, quis porttitor erat elementum. Phasellus tincidunt nisi euismod orci luctus malesuada. Pellentesque interdum, elit at facilisis consequat, nunc felis rhoncus eros, sit amet dictum massa quam ut nunc. Mauris ultrices quam at sodales maximus. Duis posuere hendrerit libero in fringilla. Ut est est, semper sit amet nisi ut, malesuada fringilla ex. Nulla nec mollis augue, sit amet scelerisque libero. Praesent accumsan aliquam felis.

Etiam ac lorem a sapien mollis vestibulum. Vestibulum velit magna, posuere quis nisi vel, venenatis volutpat nibh. Ut sed facilisis leo. Curabitur ut ante id metus eleifend pulvinar. Donec feugiat sem eget augue dignissim, a vulputate ipsum pulvinar. Sed eleifend justo a justo mollis mollis. Sed consequat dui sed imperdiet dictum.

Suspendisse eu lorem tincidunt, sagittis nulla eget, sollicitudin quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas venenatis posuere sem, sed rhoncus mi porta eget. Donec facilisis pharetra tortor, vel pharetra quam. Suspendisse ac molestie purus. Nulla lacus elit, semper sed faucibus at, molestie eget nibh. Quisque ultrices condimentum libero, et porta lectus egestas quis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris aliquam varius odio. Vestibulum at sem ac augue hendrerit congue ac nec mi. Sed a posuere metus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Morbi et malesuada neque, sed consequat risus. Sed sed malesuada turpis. Morbi non ante mauris. Etiam consequat purus tortor, eu tincidunt tortor consequat feugiat. Nulla facilisi. Sed fermentum, diam vitae condimentum varius, arcu arcu facilisis mauris, nec vehicula sem magna a elit. Donec ornare velit sed sapien laoreet pretium. Sed tempus pharetra ante, id consectetur dolor fermentum eu. Vestibulum ultricies in ipsum eu pulvinar. `
